### PR TITLE
feat: Add ESM support with dual-module setup

### PR DESCRIPTION
**Pull request by pnutmath**
### feat: Add ESM support with dual-module setup

- Configure Babel to transpile ESM (.mjs) files to CommonJS (.cjs) files
- Update package.json with build script for CommonJS generation
- Update package.json "exports" field to support both ESM and CommonJS imports
- Ensure both ESM and CommonJS files are included in the published npm package

To solve issue #5

### CODE REVIEW

**Comment by pnutmath** [comment]
@ankane Please review this.

### Test case results:

```shell
➜  pgvector-node git:(master) ✗ yarn test
yarn run v1.22.19
$ node --experimental-vm-modules ./node_modules/.bin/jest
(node:97680) ExperimentalWarning: VM Modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 PASS  src/prisma/index.test.js
 PASS  src/pg/index.test.js
  ● Console

    console.log
      rows [
        { id: 1, embedding: [ 1, 2, 3 ] },
        { id: 2, embedding: [ 1, 2, 3 ] }
      ]

      at Object.<anonymous> (src/pg/index.test.js:31:11)

 PASS  src/pg-promise/index.test.js
 PASS  src/sequelize/index.test.js

Test Suites: 4 passed, 4 total
Tests:       12 passed, 12 total
Snapshots:   0 total
Time:        1.538 s, estimated 2 s
Ran all test suites.
✨  Done in 2.19s.
```

**Comment by vishu3011** [comment]
+1 to this PR, it is required for my project also
thanks @pnutmath for raising the same

**Comment by pnutmath** [comment]
@vishu3011 You can add this package as Github repo till it gets verified and merge!

```json
"pgvector": "github:pnutmath/pgvector-node",
```

**Comment by ankane** [comment]
Hi @pnutmath, thanks for reporting and the PR. Pushed a fix in the commit above.

**Pull request closed without merging**
